#! /bin/bash

# A script used for testing pipe redirects.

echo "1";
echo "2" 1>&2;
echo "3";
echo "4" 1>&2;
echo "5";
echo "6" 1>&2;
echo "7";
echo "8" 1>&2;
echo "9";
echo "10" 1>&2;

sleep 1;
echo "normal output";

sleep 1;
echo "error output" 1>&2;


# cat "${1:-/dev/stdin}";

exit 1;
